app:
  title: "Visual Search API"
  paths:
    static: "docs/static"
    index_html: "docs/index.html" 
  base_url: "http://127.0.0.1:8000"

models:
  paths:
    face_detect_model: "models/face_detect/mediapipe"
    embeddings_model: "models/embeddings/deepface"

faiss:
  paths:
    index_path: "embeddings_store"

image:
  max_size: 1280

data:
  path: "data/"
  upload_max_workers: 8
  temp_file: "batch_processing_temp.parquet"

search:
  retrieval_similarity_threshold: 30
  min_other_images: 5
  k_to_search: 21
  save_similarity_threshold: 95



