name: Push to HuggingFace

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      # Checkout the GitHub repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          lfs: true

      # Set up SSH Agent and Trust Hugging Face
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.HF_SPACE }}
      
      - name: Trust Hugging Face Host
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan hf.co >> ~/.ssh/known_hosts

      # Clone the HF Space
      - name: Clone Hugging Face Space
        env:
          HF_USERNAME: "HrayrMuradyan"
          HF_SPACE_NAME: "find-your-twin"
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          
          git clone git@hf.co:spaces/$HF_USERNAME/$HF_SPACE_NAME hf_sync

      # Copy files
      - name: Copy specific files
        run: |
          cp pyproject.toml hf_sync/
          cp -r src/ hf_sync/
          cp -r models/ hf_sync/
          cp -r configs/ hf_sync/
          cp -r app/ hf_sync/
          cp requirements_docker.txt hf_sync/
          cp Dockerfile hf_sync/
          cp docker_start.sh hf_sync/

      # Check if there is a change in the files and push changes
      - name: Push to Hub
        env:
          HF_USERNAME: "HrayrMuradyan"
          HF_SPACE_NAME: "find-your-twin"
        run: |
          cd hf_sync
          
          if [[ -n $(git status -s) ]]; then
            git add .
            git commit -m "Sync from GitHub: ${{ github.sha }}"
            
            git push origin main
            
            echo "Successfully pushed to Hugging Face."
          else
            echo "No changes detected. Skipping push."
          fi